'use strict';
const a=require('node:assert/strict'),R=require('../research.js'),C=require('../experience-core.js');
let count=0;
const ok=(name,f)=>{f();count++;};
const track={id:'t',columns:['Average','Task','Loss'],direction:'higher',unit:'percent',comparisonScope:'protocol',columnDirections:{Loss:'lower'}};
const row=(id,v,task=v)=>({id,method:id,paperId:'p001',trackId:'t',values:{Average:v,Task:task,Loss:v},evidence:'checked',verifiedAt:'2026-09-19',source:'https://example.org/paper',sourceVersion:'v1',locator:'Table 1'});
const rows=[row('high',90,2),row('zero',0,40),row('null',null,null),row('tie',90,20)];
const copy=JSON.stringify(rows);
ok('all columns not just Average',()=>a.deepEqual(R.boardRows(rows,track,'Task').map(r=>r.id),['zero','tie','high','null']));
ok('ascending keeps null last and zero valid',()=>a.deepEqual(R.boardRows(rows,track,'Average','asc').map(r=>r.id),['zero','high','tie','null']));
ok('display direction cannot invert scientific ranks',()=>a.deepEqual(R.boardRows(rows,track,'Average','asc').map(r=>r.rank),[3,1,1,null]));
ok('default lower direction',()=>a.equal(R.boardRows(rows,{...track,direction:'lower'},'Task')[0].id,'high'));
ok('explicit metric direction takes priority',()=>a.equal(R.boardRows(rows,track,'Loss')[0].id,'zero'));
ok('source order restored',()=>a.deepEqual(R.boardRows(rows,track,'Task','source').map(r=>r.id),rows.map(r=>r.id)));
ok('paper-table reorder never gives rank',()=>a(R.boardRows(rows,{...track,comparisonScope:'paper-table'},'Task').every(r=>r.rank===null)));
ok('stable ties by method and ID',()=>a.deepEqual(R.sortRows([row('tie',2),row('high',2)],'Average').map(r=>r.id),['high','tie']));
ok('NaN infinity undefined are missing',()=>a.deepEqual(R.sortRows([row('a',Infinity),row('b',NaN),row('c',undefined),row('z',0)],'Average','asc').map(r=>r.id),['z','a','b','c']));
ok('no mutation',()=>a.equal(JSON.stringify(rows),copy));
ok('sort entire population before pagination',()=>{const x=Array.from({length:60},(_,i)=>row('r'+i,i));a.equal(R.boardRows(x,track,'Average').slice(0,20)[0].values.Average,59);});
const pp=new Map([['p001',{name:'Reporting paper',firstPublished:'2024-06-14'}],['p002',{firstPublished:'2025-01-02'}]]);
ok('exact UTC day',()=>a.equal(C.exactDay('2024-02-29'),Date.UTC(2024,1,29)));
ok('reject partial and impossible dates',()=>{for(const d of [null,'','2024','2024-06','2025-02-29','2024-02-30','2024-13-01','today','2024-01-01T00:00:00Z'])a.equal(C.exactDay(d),null);});
let d=C.scatterData(track,rows,'Average',pp);
ok('missing scores do not become zero',()=>{a.equal(d.missingScore,1);a.equal(d.validCount,3);a(d.groups.some(g=>g.value===0));});
ok('coincident rows retained not averaged',()=>{a.equal(d.groups.length,2);a.equal(d.groups.find(g=>g.value===90).points.length,2);});
ok('source paper date is not inferred method date',()=>{a.equal(d.groups[0].date,'2024-06-14');a.equal(d.oneDate,true);});
ok('single-date extent finite nonzero',()=>{a(d.start<d.end);a(Number.isFinite(d.start));});
ok('verification date separately selectable',()=>a.equal(C.scatterData(track,rows,'Average',pp,'verifiedAt').groups[0].date,'2026-09-19'));
ok('no fallback date if paper unknown',()=>{let z=C.scatterData(track,rows,'Average',{});a.equal(z.validCount,0);a.equal(z.missingDate,3);a(Number.isFinite(z.start));});
ok('no fallback from partial date',()=>a.equal(C.scatterData(track,rows,'Average',{p001:{firstPublished:'2024'}}).validCount,0));
ok('source isolation and candidates excluded',()=>{let z=C.scatterData(track,[...rows,{...row('wrong',100),trackId:'other'},{...row('draft',100),evidence:'candidate'}],'Average',pp);a.equal(z.eligible,4);});
ok('different real dates remain distinct',()=>a.equal(C.scatterData(track,[row('a',2),{...row('b',2),paperId:'p002'}],'Average',pp).groups.length,2));
ok('zero score domain percent',()=>{let z=C.scatterData(track,[row('a',0)],'Average',pp);a.equal(z.min,0);a.equal(z.max,100);});
ok('score unit and negative values not percent-converted',()=>{let z=C.scatterData({...track,unit:'score'},[row('a',-1),row('b',0.3)],'Average',pp);a.equal(z.min,-1);a.equal(z.groups[1].value,0.3);});
ok('metric fallback safe',()=>a.equal(C.scatterData(track,rows,'unknown',pp).metric,'Average'));
ok('empty selection does not manufacture a point',()=>{let z=C.scatterData(track,[],'Average',pp);a.equal(z.groups.length,0);a.equal(z.validCount,0);});
ok('10000 results bounded without silent loss',()=>{let z=C.scatterData(track,Array.from({length:10000},(_,i)=>row('r'+i,i)),'Average',pp);a.equal(z.totalGroups,10000);a.equal(z.groups.length,500);a.equal(z.plottedCount,500);a.equal(z.validCount,10000);});
ok('CSV retains excluded rows with explicit reason',()=>{const csv=C.scatterCSV(track,[...rows,{...row('unknown',1),paperId:'p999'}],'Average',pp);a(csv.includes('missing exact day'));a(csv.includes('missing numeric score'));a(csv.includes('not necessarily method release date'));a.equal(csv.split('\r\n').length,6);});
ok('CSV zero preserved and formula text escaped',()=>{const csv=C.scatterCSV(track,[{...row('z',0),method:'=1+2'}],'Average',pp);a(csv.includes('"0"'));a(csv.includes('"\'=1+2"'));});
ok('URL helper refuses executable sources',()=>a(C.scatterCSV(track,[{...row('bad',1),source:'javascript:alert(1)'}],'Average',pp).includes('"#"')));
console.log(`PASS: ${count} leaderboard sorting / scatter / source-date / scale / CSV assertions.`);
